version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titikkoma_frontend
    restart: always
    expose:
      - "80"
    networks:
      - titikkoma_network

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: titikkoma_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Use the PROXY config here
      - ./proxy.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - titikkoma_network

networks:
  titikkoma_network:
    driver: bridge